//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


using unittest;

using HAPI;

namespace test_HAPITypes
{
	public class TestQuat: TestCase<TestQuat>
	{
		Quat q0 = new Quat(0,1,2,3);
		Quat q1 = new Quat(0,0.1,0.2,0.3);
		
		public TestQuat ()
		{
		}

		public void test_add() {
			Quat q2 = q0 + q1;
		}
		public void test_sub() {
			Quat q2 = q0 - q1;
		}
		public void test_neg() {
			Quat q2 = - q1;
		}
		public void test_mul() {
			Quat q2 = q0 * 4.0;
			Quat q3 = 4.0 * q0;
			Quat q4 = q0 * q1;
		}
	}
}
