//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


using unittest;

using HAPI;


namespace test_HAPITypes
{
	public class TestRot: TestCase<TestRot>
	{
		Rot r0 = new Rot(0,1,2,3);
		Rot r1 = new Rot(0,0.1,0.2,0.3);
		
		public TestRot ()
		{
		}
		
		public void test_neg() {
			Rot r2 = - r1;
		}
		public void test_mul() {
			Rot r2 = r0 * 4.0;
			Rot r3 = 4.0 * r0;
			Rot r4 = r0 * r1;
		}
	}
}
