//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using unittest;

using HAPI;


namespace test_HAPITypes
{
	public class TestGeometryPrimitive : TestCase<TestGeometryPrimitive>
	{
		public TestGeometryPrimitive ()
		{
		}

		public void _test_createPrimitives() {
			double radius = 0.1;
			Cylinder cyl = new Cylinder (radius, 0.1);
			AABox box = new AABox(new Vec3(-0.1,-0.1,-0.1), new Vec3(0.1,0.1,0.1) );
			LineSegment ls = new LineSegment(new Vec3(-0.1,-0.1,-0.1), new Vec3(0.1,0.1,0.1) );
			Plane plane = new Plane(new Vec3(0.05,0.05,0.05), new Vec3(0.1,0.1,0.1) );
			Point point = new Point (new Vec3 (0, 0, 0));
			Sphere sphere = new Sphere (new Vec3 (0, 0, 0), radius);
			Triangle tri = new Triangle (new Vec3 (0, 0, 0), new Vec3 (-0.1, -0.1, -0.1), new Vec3 (0.1, 0.1, 0.1));

			Vec3 pt = new Vec3 (0, 0, 0);
			Constraints consts = new Constraints();
			plane.getConstraints (pt, consts);

			Vec3 pt0 = new Vec3(0,1,1), pt1= new Vec3(), normal= new Vec3(), tex= new Vec3();
			sphere.closestPoint (pt0, pt1, normal, tex);
			Vec3 pt2 = normal * radius;
			AssertEqual (pt1.x, pt2.x);
			AssertEqual (pt1.y, pt2.y);
			AssertEqual (pt1.z, pt2.z);
		}
	}
}

