//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using unittest;

using HAPI;

namespace test_HAPITypes
{
	public class TestMat3: TestCase<TestMat3>
	{
		Mat3 m0 = new Mat3(0,1,2,3,4,5,6,7,8);
		Mat3 m1 = new Mat3(0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8);
		
		public TestMat3 ()
		{
		}

		public void test_getitem() {
			double d = m0[2,2];
		}
		public void test_add() {
			Mat3 m2 = m0 + m1;
		}
		public void test_sub() {
			Mat3 m2 = m0 - m1;
		}
		public void test_neg() {
			Mat3 m2 = - m1;
		}
		public void test_mul() {
			Mat3 m2 = m0 * 4.0;
			Mat3 m3 = 4.0 * m0;
			Mat3 m4 = m0 * m1;
		}
	}
}


