//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using unittest;

using HAPI;


namespace test_HAPITypes
{
	public class TestMat4: TestCase<TestMat4>
	{
		Mat4 m0 = new Mat4(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15);
		Mat4 m1 = new Mat4(0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5);
		
		public TestMat4 ()
		{
		}
		
		public void test_getitem() {
			double d = m0[3,3];
		}
		public void test_add() {
			Mat4 m2 = m0 + m1;
		}
		public void test_sub() {
			Mat4 m2 = m0 - m1;
		}
		public void test_neg() {
			Mat4 m2 = - m1;
		}
		public void test_mul() {
			Mat4 m2 = m0 * 4.0;
			Mat4 m3 = 4.0 * m0;
			Mat4 m4 = m0 * m1;
		}
	}
}


