//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using unittest;

using HAPI;


namespace test_HAPITypes
{
	public class DummyHAPIForceEffect : HAPIForceEffect
	{
	    public DummyHAPIForceEffect() {
		}

		public override EffectOutput calculateForces(EffectInput input) {
			return new EffectOutput (new Vec3 (), new Vec3 ());
		}
	}


	public class TestForceEffect: TestCase<TestForceEffect>
	{
		EffectOutput ef0 = new EffectOutput(new Vec3(1,2,3), new Vec3(0.1,0.2,0.3) );
		EffectOutput ef1 = new EffectOutput(new Vec3(4,5,6), new Vec3(0.4,0.5,0.6) );

		public TestForceEffect ()
		{
		}

		public void test_add() {
			EffectOutput ef2 = ef0 + ef1;
		}

		public void test_mul() {
			EffectOutput ef4 = ef0 * -1.0f;
		}

		public void test_force_torque() {
			AssertTrue( csHAPI.__eq__ (new Vec3 (1, 2, 3), ef0.getForce ()) );
			AssertTrue( csHAPI.__eq__ (new Vec3 (0.1, 0.2, 0.3), ef0.getTorque ()) );
		}
	}
}

